#!/bin/bash
echo "# PHP 8.2"
echo "$(curl http://localhost:10820/info.php 2> /dev/null)"
echo ""
echo "# PHP 8.1"
echo "$(curl http://localhost:10810/info.php 2> /dev/null)"
echo ""
echo "# PHP 8.0"
echo "$(curl http://localhost:10800/info.php 2> /dev/null)"
echo ""
echo "# PHP 7.4"
echo "$(curl http://localhost:10740/info.php 2> /dev/null)"
echo ""
echo "# PHP 7.3"
echo "$(curl http://localhost:10730/info.php 2> /dev/null)"
echo ""
echo "# PHP 7.2"
echo "$(curl http://localhost:10720/info.php 2> /dev/null)"
echo ""
echo "# PHP 7.1"
echo "$(curl http://localhost:10710/info.php 2> /dev/null)"
echo ""
echo "# PHP 7.0"
echo "$(curl http://localhost:10700/info.php 2> /dev/null)"
echo ""
echo "# PHP 5.6"
echo "$(curl http://localhost:10560/info.php 2> /dev/null)"
echo ""
echo "# PHP 5.5"
echo "$(curl http://localhost:10550/info.php 2> /dev/null)"
echo ""
