#!/bin/bash
echo "# PHP 8.2"
echo "$(curl http://localhost:10820/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 8.1"
echo "$(curl http://localhost:10810/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 8.0"
echo "$(curl http://localhost:10800/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 7.4"
echo "$(curl http://localhost:10740/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 7.3"
echo "$(curl http://localhost:10730/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 7.2"
echo "$(curl http://localhost:10720/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 7.1"
echo "$(curl http://localhost:10710/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 7.0"
echo "$(curl http://localhost:10700/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 5.6"
echo "$(curl http://localhost:10560/_dockerinfo.php 2> /dev/null)"
echo ""
echo "# PHP 5.5"
echo "$(curl http://localhost:10550/_dockerinfo.php 2> /dev/null)"
echo ""
